const fs=require('fs'),assert=require('assert');
const helper=fs.readFileSync('experiments/homekit-camera/CacheTest.swift','utf8');
const begin=helper.slice(helper.indexOf('private func begin('),helper.indexOf('private func stopLiveCapture('));
assert(begin.includes('if manualTickets[id] != nil'));
assert(begin.includes('stream.startStream()'));
assert(begin.includes('control.takeSnapshot()'));
assert(begin.includes('source.removeFromSuperview()'));
assert(begin.includes('source = HMCameraView()'));
assert(helper.includes('stream.updateAudioStreamSetting(.muted)'));
assert(helper.includes('stream?.delegate = nil; stream?.stopStream()'));
assert(helper.includes('if activeID == id { stopLiveCapture();'));
assert(helper.includes('stopLiveCapture(); activeID = nil; activeControl = nil; updateStatus()'));
assert(helper.includes('Live video pixels not ready. No cached image substituted.'));
const watch=fs.readFileSync('src/c/cameras.c','utf8');
const drawing=watch.slice(watch.indexOf('static void image_draw('),watch.indexOf('static void image_disappear('));
assert(drawing.includes('graphics_draw_text(ctx,caption'));
assert(drawing.indexOf('graphics_draw_text(ctx,caption')<drawing.indexOf('else {graphics_context_set_text_color'));
assert(drawing.includes('GColorBlack')&&drawing.includes('GColorWhite'));
assert(drawing.includes('FONT_KEY_ROBOTO_CONDENSED_21'));
assert(drawing.includes('graphics_text_layout_get_content_size(caption,font'));
assert(drawing.includes('bounds.size.h-caption_height-1'));
assert(!drawing.includes('GTextOverflowModeTrailingEllipsis'));
assert(watch.includes('app_timer_register(1000,age_tick,NULL)'));
assert(watch.includes('MESSAGE_KEY_CAMERA_TIMESTAMP'));
const main=fs.readFileSync('src/c/itsyhome-pebble.c','utf8');
assert(main.includes('"Voice", NULL, NULL'));
assert(main.includes('"Refresh", NULL, NULL'));
console.log('PASS: live capture lifecycle guards, persistent outlined capture time and ticking age, Voice/Refresh without subtitles');
