const fs=require('fs'),vm=require('vm'),assert=require('assert');
assert.deepEqual(require('../src/pkjs/camera-private-config'),{});
assert(fs.readFileSync('src/c/pome_features.h','utf8').includes('#define POME_EXPERIMENTAL_CAMERAS 1'));
assert(fs.readFileSync('src/c/cameras.c','utf8').includes('#if defined(PBL_PLATFORM_EMERY) && POME_EXPERIMENTAL_CAMERAS'));
let state;
const context={module:{exports:{}},require:n=>require('../src/pkjs/'+n.slice(2)),localStorage:{getItem:()=>null},Pebble:{addEventListener(){}},XMLHttpRequest:function(){throw Error('Unpaired cameras must not access network');}};
vm.runInNewContext(fs.readFileSync('src/pkjs/cameras.js','utf8'),context);
context.module.exports.settings(s=>state=s);
assert.strictEqual(state.enabled,true);
assert(state.error.includes('pair your Connector'));
const settings=require('../src/pkjs/camera-settings');
const html=settings.augment('<div class="toggle"><label><input type="checkbox" id="cameras" checked>Cameras</label></div><p>Old camera help</p><h2>Light colors</h2><script>function save(){}</script>',{...state,home:{revision:1,items:[{token:0,name:'Voice',type:'Section'}]}});
assert(html.includes('id="camerasPanel"'));assert(html.includes('id="cameraToken"'));assert(html.includes('id="cameraUrl"'));
assert(!html.includes('id="cameras" hidden disabled'));assert(!html.includes('not included in this public release'));
const script=html.match(/<script>([^]*)<\/script>/)[1];
const values={cameraPan:{value:'3'},cameraMode:{value:'natural'},cameraUrl:{value:''},cameraToken:{value:''}};
const browser={window:{addEventListener(){}},document:{getElementById:id=>values[id]||null,querySelectorAll:()=>[]}};
vm.runInNewContext(script,browser);assert.equal(browser.readCameraConfig().home,null);
const watch=fs.readFileSync('src/c/itsyhome-pebble.c','utf8');
for(const name of ['theme','settings','pin','shortcut','shortcut_target'])assert(!watch.includes('s_'+name+'_window = window_create()'));
console.log('PASS: camera-enabled public candidate, blank pairing/no unconfigured network access, settings save and obsolete windows not allocated');
