const {test}=require('node:test'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
function check(source,setup,main){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'organik-buttons-'));try{fs.writeFileSync(path.join(dir,'test.c'),'#include <stdbool.h>\n#include <stdint.h>\n#include <stddef.h>\n#include <string.h>\n#include <assert.h>\n'+setup+'\n'+source+'\nint main(void){'+main+'}');execFileSync('cc',[path.join(dir,'test.c'),'-o',path.join(dir,'test')]);execFileSync(path.join(dir,'test'));}finally{fs.rmSync(dir,{recursive:true,force:true});}}

test('Double Back dispatches Pome shortcuts while obsolete theme shortcuts remain inert',()=>{
 const src=fs.readFileSync(path.join(__dirname,'../src/c/itsyhome-pebble.c'),'utf8');
 const run=src.slice(src.indexOf('static void run_shortcut('),src.indexOf('static void root_long_click('));
 const back=src.slice(src.indexOf('static void root_double_back('),src.indexOf('static void root_shortcut_click_config_provider(void *context) {'));
 check(run+back,`typedef int ClickRecognizerRef;static char*s_shortcut_double_back="off";enum{ITEM_KIND_FAVORITE=1,ITEM_KIND_SCENE,ITEM_KIND_ROOM};static int opened,voice,scenes,pins;static void toggle_highlighted_scene_pin(void){pins++;}static void vibes_short_pulse(void){}static void start_voice(void){voice++;}static void push_list(int kind){opened=kind;}static void run_scene(const char*name){assert(!strcmp(name,"Lights"));scenes++;}`,
 `root_double_back(0,0);assert(!opened&&!voice&&!scenes);s_shortcut_double_back="scenes";root_double_back(0,0);assert(opened==ITEM_KIND_SCENE);s_shortcut_double_back="scene:Lights";root_double_back(0,0);assert(scenes==1);s_shortcut_double_back="themes";opened=0;root_double_back(0,0);assert(!opened&&scenes==1);s_shortcut_double_back="pin_toggle";root_double_back(0,0);assert(pins==1);`);
});

test('Pin shortcut targets highlighted scenes and pinned root rows, never rooms or action rows',()=>{
 const src=fs.readFileSync(path.join(__dirname,'../src/c/itsyhome-pebble.c'),'utf8');
 const body=src.slice(src.indexOf('static void toggle_highlighted_scene_pin('),src.indexOf('static void run_shortcut('));
 check(body,`#include <stdio.h>
#define MAX_NAME_LENGTH 64
 typedef struct{char room[64],id[40],type[24];uint8_t sensor;}PinAccessory;static PinAccessory last_accessory;
 typedef void Window;typedef struct{int section,row;}MenuIndex;
#define MenuIndex(s,r) ((MenuIndex){s,r})
 enum{ITEM_KIND_SCENE,ITEM_KIND_ROOM,MenuRowAlignNone};static void*s_root_window=(void*)1,*s_list_window=(void*)2,*s_room_scene_window=(void*)3,*top;static void*s_root_menu=(void*)1,*s_list_menu=(void*)2,*s_room_scene_menu=(void*)3;static int row,s_pin_count=1,s_room_scene_count=1,s_current_kind,changes;static char last[64];static bool fail;
 static void *s_device_window=(void*)4,*s_sensor_window=(void*)5,*s_device_menu=(void*)4,*s_sensor_menu=(void*)5;static bool s_device_loading;static char s_device_error[1],s_selected_room[64]="Office",s_device_ids[1][40]={"service-1"};static int s_device_count=1,s_sensor_count=1;static struct{char name[64],type[24];}s_devices[]={{"Lamp","light"}},s_sensors[]={{"Temperature","temperature"}};static int sensors_visible(void){return 0;}static int light_count(void){return 1;}static bool pin_accessory(int row,PinAccessory*a){return false;}
 static struct Scene{char name[64];}items[]={{"Favorite"},{"Scene"}},s_room_scenes[]={{"Room scene"}};
 static int list_count(void){return 2;}static struct Scene*list_items(void){return items;}static void*window_stack_get_top_window(void){return top;}static MenuIndex menu_layer_get_selected_index(void*m){return(MenuIndex){0,row};}static void pin_name(int r,char*n){strcpy(n,"Old pinned scene");}static bool toggle_pin_record(const char*n,const PinAccessory*a){if(a)last_accessory=*a;strcpy(last,n);changes++;return !fail;}static void show_voice_info(const char*t){}static void marquee_reset(void){}static int root_get_num_rows(void*m,int section,void*c){return 3;}static void menu_layer_reload_data(void*m){}static void menu_layer_set_selected_index(void*m,MenuIndex i,int align,bool animated){row=i.row;}`,
 `top=s_list_window;row=1;toggle_highlighted_scene_pin();assert(!strcmp(last,"Scene")&&changes==1);s_current_kind=ITEM_KIND_ROOM;toggle_highlighted_scene_pin();assert(changes==1);top=s_room_scene_window;row=0;toggle_highlighted_scene_pin();assert(!strcmp(last,"Room scene")&&changes==2);top=s_root_window;row=0;toggle_highlighted_scene_pin();assert(!strcmp(last,"Old pinned scene")&&changes==3);row=1;toggle_highlighted_scene_pin();assert(changes==3);top=s_list_window;s_current_kind=ITEM_KIND_SCENE;row=9;toggle_highlighted_scene_pin();assert(changes==3);top=s_device_window;row=1;toggle_highlighted_scene_pin();assert(changes==3);row=2;toggle_highlighted_scene_pin();assert(changes==4&&!strcmp(last,"Lamp")&&!strcmp(last_accessory.id,"service-1")&&!strcmp(last_accessory.room,"Office"));top=s_sensor_window;row=0;toggle_highlighted_scene_pin();assert(changes==5&&last_accessory.sensor==1);`);
});
test('opening accessory pins focuses only a uniquely matching refreshed item and never actuates it',()=>{
 const src=fs.readFileSync(path.join(__dirname,'../src/c/itsyhome-pebble.c'),'utf8');
 const body=src.slice(src.indexOf('static void focus_open_pin('),src.indexOf('static void inbox_received('));
 check(body,`typedef struct{int section,row;}MenuIndex;
#define MenuIndex(s,r) ((MenuIndex){s,r})
 enum{MenuRowAlignCenter};static struct{char room[64],id[40],type[24];uint8_t sensor;}s_open_pin;static char s_open_pin_name[64];static int s_sensor_count=1,s_device_count=2,selected=-1,errors,pushes;static void*s_sensor_window=(void*)1,*s_sensor_menu=(void*)1,*s_device_menu=(void*)2;static struct{char name[64],type[24];}s_devices[]={{"Renamed lamp","light"},{"Lamp","light"}},s_sensors[]={{"Temp","temperature"}};static char s_device_ids[2][40]={"id1","id2"};static void show_voice_info(const char*t){errors++;}static void window_stack_push(void*w,bool animated){pushes++;}static void menu_layer_set_selected_index(void*m,MenuIndex i,int align,bool animated){selected=i.row;}static int sensors_visible(void){return 1;}static int light_count(void){return 1;}`,
 `strcpy(s_open_pin_name,"Old lamp");strcpy(s_open_pin.id,"id1");focus_open_pin();assert(selected==3&&!errors&&!s_open_pin_name[0]);strcpy(s_open_pin_name,"Old lamp");strcpy(s_device_ids[1],"id1");focus_open_pin();assert(errors==1&&selected==3);s_open_pin.sensor=1;s_open_pin.id[0]=0;strcpy(s_open_pin.type,"temperature");strcpy(s_open_pin_name,"Temp");focus_open_pin();assert(pushes==1&&selected==0);strcpy(s_open_pin_name,"Missing");focus_open_pin();assert(errors==2&&pushes==1);`);
});
